defaults: &defaults
  token: 16683e05a8ea2167321958a1bbd77d65f2f8a2ee751d85e951022317eba0835b9f1229c3eecac185584af3b61262e390b195dee85610b672bcc1492fb9e2f816
  app_name: DVD
  noreply: noreply@dvd-test.heroku.com
  host: localhost:3000
  identities:
    twitter:
      key: Ank92dam8rUTSfBtxN7AWg
      secret: kl95VO9BWzb6a4NL8dZJbosJMm4kmiGPoC0LKvdV6OI

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: dvd-test.heroku.com
